version: "3.9"

services:
  tts:
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app
      # - tts-static-data:/vol/web

    command: >
      bash -c 'while !</dev/tcp/tts_db/5432; do sleep 1; done; uvicorn main:app --reload --host 0.0.0.0'

    environment:
      - DATABASE_URL=postgresql://tts_user:testpass@tts_db:5432/tts

    depends_on:
      - tts_db

  tts_db:
    image: postgres:13-alpine
    volumes:
      - tts-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tts
      - POSTGRES_USER=tts_user
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"

volumes:
  tts-data: # tts-static-data:
